### ISSUE TITLE
Golang Twitter bot tutorial does not include instructions to import packages from go-twitter module.

### ISSUE THREAD

**Issue by fchikwekwe** [elliotforbes/tutorialedge-v2#12]
I would have opened a PR for this, but I did not want to mess around with the way your excellent content is organized. In the Golang Twitter bot tutorial, it mentions that we are using packages from go-twitter, but does not tell the us to import those files. The "oauth-1" and "twitter" variables throw errors without this import. 

This might be a small thing, but for someone who is still getting used to Golang, it would be helpful to state that and include those lines of code in the tutorial. 

The go-twitter documentation does include an example of this import (https://godoc.org/github.com/dghubble/go-twitter/twitter). 

```// OAuth1
import (
	"github.com/dghubble/go-twitter/twitter"
	"github.com/dghubble/oauth1"
)

config := oauth1.NewConfig("consumerKey", "consumerSecret")
token := oauth1.NewToken("accessToken", "accessSecret")
// http.Client will automatically authorize Requests
httpClient := config.Client(oauth1.NoContext, token)

// twitter client
client := twitter.NewClient(httpClient)

**Comment by elliotforbes** [comment]
Absolutely, I'm sorry I missed this and caused you some issues! I've added in the imports to the article!

**Comment by fchikwekwe** [comment]
Thank you! Great tutorial!
